version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: data from Greenweez regarding products, sales and ships
    tables: 
      - name: product
        identifier: raw_gz_product
        description: product id of all products for Greenweez
        tests:
          - unique:
              column_name: products_id
          - not_null: 
              column_name: products_id

      - name: sales
        identifier: raw_gz_sales
        description: sales for Greenweez
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          - not_null: 
              column_name: "(orders_id || '-' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: all ships for Greenweez
        tests:
          - unique:
              column_name: orders_id
          - not_null: 
              column_name: orders_id

